### ISSUE TITLE
Create media queries for each page 

### ISSUE THREAD

**Issue by christinalewis58** [LMarsiske/MMC6278-10-10-Brose-Lewis-Marsiske-Poppenwimer#11]
Each page of the website needs 1-2 media queries to respond to larger screens

**Comment by tkatpop** [comment]
I started the responsive coding for brewery page. Have not applied hamburger menu yet for smaller screens.

**Comment by tkatpop** [comment]
Hamburger menu is complete for brewery page, javascript for it is on the bottom of the brewery js page, styling is in the brewery section and under media queries, used Google Material Icon instead of png; the code can be easily transferred over to other pages.
